config/routes.rb
Rails.application.routes.draw do
  get "posts/aboutus"
  get "products/index"
  get "products/slugtee1"
  get "products/slugtee2"
  get "products/landing"

  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  resources :products
  resources :carted_items



  ####root creates a landing page, whenever we edit routes, we should restart server
  root "products#landing"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :carteditem

end

app/models/carted_item.rb
class CartedItem < ApplicationRecord
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :carted_item
  accepts_nested_attributes_for :carted_item
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carted_items_controller.rb
class CartedItemsController < ApplicationController

  def index # Prob don't need this
    @carted_item = CartedItem.order(created_at: :desc)
  end

  def new # Prob don't need this
    @carted_item = CartedItem.new
  end

  def create# Prob don't need this
    @carted_item = CartedItem.new(post_params)
    if @carted_item.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit# Prob don't need this
    @carted_item = CartedItem.find(params[:id])
  end

  private
  def post_params
    params.require(:carteditem).permit(:quantity, :size, :product_id)
  end

end

app/controllers/example_controller.rb
class ExampleController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id]) #finds the post by the ID
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
        redirect_to @post
    else
        render 'edit'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path

  end


  private

  #Security feature which limits data types for submission to Database
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index # Need this
    @product = Product.order(created_at: :desc)
  end

  def new # Prob don't need this
    @product = Product.new
    @carted_item = @product.carted_item.build
  end

  def create# Prob don't need this
    @product = Product.new(post_params)
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def edit# Prob don't need this
    @product = Product.find(params[:id])
  end

  def show #Shows the product page
    @product = Product.find(params[:id]) #finds the post by the ID
    @carted_item = @product.carted_item.build
  end

  def destroy # Prob don't need this
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end


  def update
  end


  private

  def post_params #prob don't need this
    params.require(:product).permit(:title, :description, carted_item_attributes: [:quantity, :size, :product_id])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carted_items_helper.rb
module CartedItemsHelper
end

app/helpers/example_helper.rb
module ExampleHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>SLUG</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<!--<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Playfair+Display+SC&display=swap">
   <style>
     body {
      font-family: 'Playfair Display SC', serif;
     }
   </style>-->
</head>

<body>

  <nav class="navbar navbar-expand-md  justify-content-start">
    <div><%= link_to image_tag("Sluglifetitleclear.png", class: "logo"), root_path%></div>
          <ul class="navbar-nav mx-auto text-left">
              <li class="nav-item navspec">
                  <%= link_to 'LOOKBOOK', root_path, class: "nav-link navtext" %>
              </li>
              <div class = "nav-item navspec nav-link navtext"> - </div>
              <li class="nav-item my-auto navspec">
                <%= link_to 'SHOP', products_index_path, class: "nav-link navtext" %>
              </li>
              <div class = "nav-item navspec nav-link navtext"> - </div>
              <li class="nav-item navspec">
                <%= link_to 'CONTACT', posts_aboutus_path, class: "nav-link navtext" %>
              </li>
          </ul>
    <div class = "navcart navitem navspec">
      <%= link_to root_path do %>
        <%= fa_icon "shopping-cart", class: "nav-link navtext navcart" %>
      <% end %>
    </div>
  </nav>




  <% if false %>

    <% end %>
  <%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<div class="section">
<%= simple_form_for @post do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
    </div>
  </div>
  <%= f.button :submit, 'Update Post', class: "button is-primary" %>
<% end %>
</div>

app/views/posts/aboutus.html.erb
<% content_for :page_title,  "About Us" %>

<div class = "section row">
  <div class = "intro">
    <h1>Contact Information</h1>
    <h1> </h1>
    <div class = "introbody">
      <p> Filler Lol</p>
    </div>
    <div class = "sluglifelogo">

    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% content_for :page_title, "Edit Post" %>
<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :page_title,  "Slug Life" %>
<div class="first">
  <!-- Hero head: will stick at the top -->
  <!-- Hero content: will be in the middle -->

</div>
<!--

-->

app/views/posts/new.html.erb
<% content_for :page_title,  "What's On Your Mind?" %>
<div class="section">
<%= simple_form_for @post do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
    </div>
  </div>
  <%= f.button :submit, 'Create new post', class: "button is-primary" %>
<% end %>
</div>

app/views/posts/show.html.erb
<% content_for :page_title,  @post.title %>
<section class = "section">
  <div class = "container">
    <nav class="level">
		  <!-- Left side -->
		  <div class="level-left">
		    <p class="level-item">
		        <strong>Actions</strong>
		    </p>
		  </div>
		  <!-- Right side -->
		  <div class="level-right">
		  	<p class="level-item">
		    	<%= link_to "Edit", edit_post_path(@post), class:"button" %>
		  	</p>
		  	<p class="level-item">
				  <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class:"button is-danger" %>
				</p>
		  </div>
		</nav>
		<hr/>

    <% if false %>
    This removes the title from showing up twice, the code above implements the delete/edit buttons
    <h1 class = "title">
      <%= @post.title %>
    </h1>

    <% end %>
    <div class = "content">
      <%= @post.content %>
    </div>
  </div>
</section>

app/views/products/index.html.erb
<div class = "super">
  <div class="conatiner a">
    <div class="wrap a">
      <% @product.each do |prod| %>
      <div class="box a">
        <div class = "prod_img imagefor<%= prod.id%>">
          <div class="info">
            <button class="button" name="cart">
              <%= link_to 'VIEW', prod, class: "vbutton"  %>
            </button>
          </div>
          <div class = "subtitle"><%= link_to prod.title, prod, class:"subtitle"  %>
            <div class = "subprc"> $ <%= prod.price %>0</div></div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/products/landing.html.erb
<div class = "hero-image"></div>

app/views/products/show.html.erb
<% content_for :product_title,  @product.title %>



<div class ="a">
  <div class = "prodhead"><h1>
   </h1></div>
  <div class = "prodinfo">
  <div class = 'prodcol prodleft tee imagefor<%= @product.id%>'></div>
  <div class = 'prodcol prodright'>
    <div class = "prodtitle">
      <h2>
        <%= @product.title %>
      </h2>
      <div class="proddesc">
        <%= @product.description %>
        <div class = "proddetails"> 100% Slug </div>

      </div>
        <div>
          <%= form_for @product do |f| %>
          FORM PASS
          <!-- contract fields -->
          <ul>
            <%= f.fields_for :carted_item do |carted_items_form| %>
            <li>
              <%= carted_items_form.select :quantity, [['1','one'],['2','two'],['3','three']] %>
              <%= carted_items_form.select :size, [['S','s'],['M','m'],['L','l']] %>
              <!-- products object is lacking a submit fcn -->
              <%= carted_items_form.button :submit %>
              <button class = "atcbtn">
              </button>
            </li>
            <% end %>
          </ul>
          <% end %>
      </div>
    </div>
  </div>
  </div>
</div>

app/views/products/slugtee1.html.erb
<div>
  <div class = "prodhead"><h1> CIGARETTE TEE - WHITE </h1></div>
  <div class = "prodinfo">
  <div class = 'prodcol prodleft teeone'></div>
  <div class = 'prodcol prodright'>
    <div class = "prodtitle">
      <h4>CIGARETTE TEE 2019</h4>
      <div class="proddesc"> What the fuck did you just fucking say about me, you little bitch? I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces. You are nothing to me but just another target.
        <div class = "proddetails"> 50% Cotton, 50% Polyester, 100% Slug </div>

      </div>
      <div><button class = "button"> ADD TO CART </button>
      </div>
    </div>
  </div>
  </div>
</div>

app/views/products/slugtee2.html.erb
<h1> BOOBIES TEE </h1>

<div>
  <div class = 'prodcol prodleft teetwo'></div>
  <div class = 'prodcol prodright'>
    <div class = "prodtitle">
      <h4>Optional Title But It's Kinda Ugly</h4>
      <div class="proddesc">
        C'mon guys, I'm not THAT sus
            <div><button class = "atcproduct"> ADD TO CART </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/view_product.html.erb
<% content_for :prod_title,  @prod.title %>

<div class = "content">
  <div class = "desc">
    <div class="title">
      <%= prod.title %>
    </div>
    <div class="info">
      <%= prod.description %>
      <div><button class="button" name="cart">ADD TO CART</button></div>
    </div>
  </div>
</div>